# Generated by Django 4.2.1 on 2023-08-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plageaddressip',
            name='masque',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
