# Generated by Django 4.2.1 on 2023-08-08 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_plageaddressip_masque'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlageAddressIP',
            new_name='SousReseau',
        ),
    ]
