# Generated by Django 4.2.1 on 2023-08-08 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_plageaddressip_sousreseau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='nomDepart',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sousreseau',
            name='addressIP',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='sousreseau',
            name='masque',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='PlageAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresseDiffus', models.CharField(max_length=25)),
                ('nbHote', models.IntegerField()),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.departement')),
                ('sousReseau', models.ManyToManyField(to='myapp.sousreseau')),
            ],
        ),
    ]
