# Generated by Django 4.2.1 on 2023-08-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_departement_nomdepart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plageadress',
            old_name='adresseDiffus',
            new_name='addrReseau',
        ),
        migrations.RenameField(
            model_name='plageadress',
            old_name='nbHote',
            new_name='nbPC',
        ),
        migrations.RemoveField(
            model_name='plageadress',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='plageadress',
            name='sousReseau',
        ),
        migrations.AddField(
            model_name='plageadress',
            name='broadcast',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plageadress',
            name='hostmask',
            field=models.CharField(default='192.168.0.0', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plageadress',
            name='nbPCMax',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plageadress',
            name='nomSousReseau',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plageadress',
            name='passerelle',
            field=models.CharField(default='1', max_length=25),
            preserve_default=False,
        ),
    ]
