# Generated by Django 4.2.1 on 2023-08-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_adressediffus_plageadress_addrreseau_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlageAdress',
        ),
    ]
